# Generated by Django 6.0.1 on 2026-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketattachment_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
