# Generated by Django 6.0.1 on 2026-03-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket'),
        ),
    ]
